//! GENERATED by kirgen — do not edit. Regenerate: cargo run --manifest-path ../kirgen/Cargo.toml
//!
//! Certificates for expression kernels (target spec_kernels::*) and loop
//! kernels (target the generated model_* recursive spec fns, which are the
//! kernels' canonical functional specs). Chain: source exec == spec == KIR.

use vstd::prelude::*;
use crate::kir::*;
use crate::addloop::mk_state;
use crate::addloop::{u_keval_loc, u_keval_addw, u_keval_ltu, u_keval_reada, u_keval_readb};
use crate::addloop::{u_kexec_assign, u_kexec_writeout, u_kloop_step, u_kloop_done};
use crate::spec_kernels::*;

verus! {

// Generic one-step unfolds for the extended op set (schema; empty bodies).

pub proof fn u_keval_subw(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::SubW(Box::new(x), Box::new(y)), st, bufa, bufb)
            == wsub(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_mulw(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::MulW(Box::new(x), Box::new(y)), st, bufa, bufb)
            == wmul(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_geu(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::GeU(Box::new(x), Box::new(y)), st, bufa, bufb)
            == geu(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_leu(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::LeU(Box::new(x), Box::new(y)), st, bufa, bufb)
            == leu(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_select(c: KExpr, t: KExpr, e: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::Select(Box::new(c), Box::new(t), Box::new(e)), st, bufa, bufb)
            == (if keval(c, st, bufa, bufb) != 0 {
                keval(t, st, bufa, bufb)
            } else {
                keval(e, st, bufa, bufb)
            }),
{
}

// ══════════ expression kernel: abs_delta ══════════

pub open spec fn stmt_abs_delta_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))) }
}

pub open spec fn body_abs_delta() -> KStmt { stmt_abs_delta_0() }

pub proof fn u_seq_abs_delta_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures kexec(body_abs_delta(), st, bufa, bufb) == kexec(stmt_abs_delta_0(), st, bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_abs_delta(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, a: u32, b: u32, n: u32)
    requires
        st.locals.len() == 4,
        st.locals[0] == a,
        st.locals[1] == b,
        st.locals[2] == n,
        1 <= n,
        n <= 1024,
        a < n,
        b < n,
    ensures
        kexec(body_abs_delta(), st, bufa, bufb).locals.len() == 4,
        kexec(body_abs_delta(), st, bufa, bufb).locals[3] as int == spec_abs_delta(a as int, b as int),
{
    let vabs_delta_0 = (if geu(a, b) != 0 { wsub(a, b) } else { wsub(b, a) });
    let llabs_delta_0 = st.locals.update(3, vabs_delta_0);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vabs_delta_0);
    assert(llabs_delta_0.len() == 4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vabs_delta_0);
    assert(llabs_delta_0[0] == a && llabs_delta_0[1] == b && llabs_delta_0[2] == n && llabs_delta_0[3] == vabs_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_abs_delta_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_geu(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(1), KExpr::Loc(0), st, bufa, bufb);
    u_keval_select(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    u_kexec_assign(3, KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))), st, bufa, bufb);
    let sabs_delta_0 = mk_state(llabs_delta_0, st.out);
    assert(kexec(stmt_abs_delta_0(), st, bufa, bufb) == sabs_delta_0 && sabs_delta_0.locals == llabs_delta_0 && sabs_delta_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_abs_delta_0, addloop.mk_state]
    };

    assert(kexec(body_abs_delta(), st, bufa, bufb) == sabs_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert(vabs_delta_0 as int == spec_abs_delta(a as int, b as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_abs_delta, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

// ══════════ expression kernel: wrap_delta ══════════

pub open spec fn stmt_wrap_delta_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))) }
}

pub open spec fn stmt_wrap_delta_1() -> KStmt {
    KStmt::Assign { loc: 4, rhs: KExpr::SubW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))) }
}

pub open spec fn stmt_wrap_delta_2() -> KStmt {
    KStmt::Assign { loc: 5, rhs: KExpr::Select(Box::new(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4)))), Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))) }
}

pub open spec fn chain_wrap_delta_1() -> KStmt {
    KStmt::Seq2(Box::new(stmt_wrap_delta_1()), Box::new(stmt_wrap_delta_2()))
}

pub open spec fn chain_wrap_delta_0() -> KStmt {
    KStmt::Seq2(Box::new(stmt_wrap_delta_0()), Box::new(chain_wrap_delta_1()))
}

pub open spec fn body_wrap_delta() -> KStmt { chain_wrap_delta_0() }

pub proof fn u_seq_wrap_delta_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(body_wrap_delta(), st, bufa, bufb)
            == kexec(chain_wrap_delta_1(), kexec(stmt_wrap_delta_0(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_wrap_delta_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_wrap_delta_1(), st, bufa, bufb)
            == kexec(stmt_wrap_delta_2(), kexec(stmt_wrap_delta_1(), st, bufa, bufb), bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_wrap_delta(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, a: u32, b: u32, n: u32)
    requires
        st.locals.len() == 6,
        st.locals[0] == a,
        st.locals[1] == b,
        st.locals[2] == n,
        1 <= n,
        n <= 1024,
        a < n,
        b < n,
    ensures
        kexec(body_wrap_delta(), st, bufa, bufb).locals.len() == 6,
        kexec(body_wrap_delta(), st, bufa, bufb).locals[5] as int == spec_wrap_delta(a as int, b as int, n as int),
{
    let vwrap_delta_0 = (if geu(a, b) != 0 { wsub(a, b) } else { wsub(b, a) });
    let vwrap_delta_1 = wsub(n, vwrap_delta_0);
    let vwrap_delta_2 = (if leu(vwrap_delta_0, vwrap_delta_1) != 0 { vwrap_delta_0 } else { vwrap_delta_1 });
    let llwrap_delta_0 = st.locals.update(3, vwrap_delta_0);
    let llwrap_delta_1 = llwrap_delta_0.update(4, vwrap_delta_1);
    let llwrap_delta_2 = llwrap_delta_1.update(5, vwrap_delta_2);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_len::<u32>(llwrap_delta_0, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_len::<u32>(llwrap_delta_1, 5, vwrap_delta_2);
    assert(llwrap_delta_0.len() == 6 && llwrap_delta_1.len() == 6 && llwrap_delta_2.len() == 6) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vwrap_delta_0);
    assert(llwrap_delta_0[0] == a && llwrap_delta_0[1] == b && llwrap_delta_0[2] == n && llwrap_delta_0[3] == vwrap_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 0, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 1, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 2, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 3, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_same::<u32>(llwrap_delta_0, 4, vwrap_delta_1);
    assert(llwrap_delta_1[0] == a && llwrap_delta_1[1] == b && llwrap_delta_1[2] == n && llwrap_delta_1[3] == vwrap_delta_0 && llwrap_delta_1[4] == vwrap_delta_1) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 0, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 1, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 2, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 3, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 4, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_same::<u32>(llwrap_delta_1, 5, vwrap_delta_2);
    assert(llwrap_delta_2[0] == a && llwrap_delta_2[1] == b && llwrap_delta_2[2] == n && llwrap_delta_2[3] == vwrap_delta_0 && llwrap_delta_2[4] == vwrap_delta_1 && llwrap_delta_2[5] == vwrap_delta_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_wrap_delta_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_geu(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(1), KExpr::Loc(0), st, bufa, bufb);
    u_keval_select(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    u_kexec_assign(3, KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))), st, bufa, bufb);
    let swrap_delta_0 = mk_state(llwrap_delta_0, st.out);
    assert(kexec(stmt_wrap_delta_0(), st, bufa, bufb) == swrap_delta_0 && swrap_delta_0.locals == llwrap_delta_0 && swrap_delta_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_0, addloop.mk_state]
    };

    u_seq_wrap_delta_1(swrap_delta_0, bufa, bufb);
    u_keval_loc(2, swrap_delta_0, bufa, bufb);
    u_keval_loc(3, swrap_delta_0, bufa, bufb);
    u_keval_subw(KExpr::Loc(2), KExpr::Loc(3), swrap_delta_0, bufa, bufb);
    u_kexec_assign(4, KExpr::SubW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))), swrap_delta_0, bufa, bufb);
    let swrap_delta_1 = mk_state(llwrap_delta_1, st.out);
    assert(kexec(stmt_wrap_delta_1(), swrap_delta_0, bufa, bufb) == swrap_delta_1 && swrap_delta_1.locals == llwrap_delta_1 && swrap_delta_1.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_1, addloop.mk_state]
    };

    u_keval_loc(3, swrap_delta_1, bufa, bufb);
    u_keval_loc(4, swrap_delta_1, bufa, bufb);
    u_keval_leu(KExpr::Loc(3), KExpr::Loc(4), swrap_delta_1, bufa, bufb);
    u_keval_loc(3, swrap_delta_1, bufa, bufb);
    u_keval_loc(4, swrap_delta_1, bufa, bufb);
    u_keval_select(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), KExpr::Loc(3), KExpr::Loc(4), swrap_delta_1, bufa, bufb);
    u_kexec_assign(5, KExpr::Select(Box::new(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4)))), Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), swrap_delta_1, bufa, bufb);
    let swrap_delta_2 = mk_state(llwrap_delta_2, st.out);
    assert(kexec(stmt_wrap_delta_2(), swrap_delta_1, bufa, bufb) == swrap_delta_2 && swrap_delta_2.locals == llwrap_delta_2 && swrap_delta_2.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_2, addloop.mk_state]
    };

    assert(kexec(body_wrap_delta(), st, bufa, bufb) == swrap_delta_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert(vwrap_delta_2 as int == spec_wrap_delta(a as int, b as int, n as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_wrap_delta, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

// ══════════ expression kernel: sum_sq3 ══════════

pub open spec fn stmt_sum_sq3_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::MulW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(0))) }
}

pub open spec fn stmt_sum_sq3_1() -> KStmt {
    KStmt::Assign { loc: 4, rhs: KExpr::MulW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(1))) }
}

pub open spec fn stmt_sum_sq3_2() -> KStmt {
    KStmt::Assign { loc: 5, rhs: KExpr::MulW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(2))) }
}

pub open spec fn stmt_sum_sq3_3() -> KStmt {
    KStmt::Assign { loc: 6, rhs: KExpr::AddW(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))) }
}

pub open spec fn stmt_sum_sq3_4() -> KStmt {
    KStmt::Assign { loc: 7, rhs: KExpr::AddW(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(5))) }
}

pub open spec fn chain_sum_sq3_3() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_3()), Box::new(stmt_sum_sq3_4()))
}

pub open spec fn chain_sum_sq3_2() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_2()), Box::new(chain_sum_sq3_3()))
}

pub open spec fn chain_sum_sq3_1() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_1()), Box::new(chain_sum_sq3_2()))
}

pub open spec fn chain_sum_sq3_0() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_0()), Box::new(chain_sum_sq3_1()))
}

pub open spec fn body_sum_sq3() -> KStmt { chain_sum_sq3_0() }

pub proof fn u_seq_sum_sq3_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(body_sum_sq3(), st, bufa, bufb)
            == kexec(chain_sum_sq3_1(), kexec(stmt_sum_sq3_0(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_1(), st, bufa, bufb)
            == kexec(chain_sum_sq3_2(), kexec(stmt_sum_sq3_1(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_2(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_2(), st, bufa, bufb)
            == kexec(chain_sum_sq3_3(), kexec(stmt_sum_sq3_2(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_3(), st, bufa, bufb)
            == kexec(stmt_sum_sq3_4(), kexec(stmt_sum_sq3_3(), st, bufa, bufb), bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_sum_sq3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, dx: u32, dy: u32, dz: u32)
    requires
        st.locals.len() == 8,
        st.locals[0] == dx,
        st.locals[1] == dy,
        st.locals[2] == dz,
        dx <= 512,
        dy <= 512,
        dz <= 1023,
    ensures
        kexec(body_sum_sq3(), st, bufa, bufb).locals.len() == 8,
        kexec(body_sum_sq3(), st, bufa, bufb).locals[7] as int == spec_sum_sq3(dx as int, dy as int, dz as int),
{
    let vsum_sq3_0 = wmul(dx, dx);
    let vsum_sq3_1 = wmul(dy, dy);
    let vsum_sq3_2 = wmul(dz, dz);
    let vsum_sq3_3 = wadd(vsum_sq3_0, vsum_sq3_1);
    let vsum_sq3_4 = wadd(vsum_sq3_3, vsum_sq3_2);
    let llsum_sq3_0 = st.locals.update(3, vsum_sq3_0);
    let llsum_sq3_1 = llsum_sq3_0.update(4, vsum_sq3_1);
    let llsum_sq3_2 = llsum_sq3_1.update(5, vsum_sq3_2);
    let llsum_sq3_3 = llsum_sq3_2.update(6, vsum_sq3_3);
    let llsum_sq3_4 = llsum_sq3_3.update(7, vsum_sq3_4);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_0, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_1, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_2, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_3, 7, vsum_sq3_4);
    assert(llsum_sq3_0.len() == 8 && llsum_sq3_1.len() == 8 && llsum_sq3_2.len() == 8 && llsum_sq3_3.len() == 8 && llsum_sq3_4.len() == 8) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vsum_sq3_0);
    assert(llsum_sq3_0[0] == dx && llsum_sq3_0[1] == dy && llsum_sq3_0[2] == dz && llsum_sq3_0[3] == vsum_sq3_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 0, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 1, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 2, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 3, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_0, 4, vsum_sq3_1);
    assert(llsum_sq3_1[0] == dx && llsum_sq3_1[1] == dy && llsum_sq3_1[2] == dz && llsum_sq3_1[3] == vsum_sq3_0 && llsum_sq3_1[4] == vsum_sq3_1) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 0, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 1, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 2, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 3, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 4, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_1, 5, vsum_sq3_2);
    assert(llsum_sq3_2[0] == dx && llsum_sq3_2[1] == dy && llsum_sq3_2[2] == dz && llsum_sq3_2[3] == vsum_sq3_0 && llsum_sq3_2[4] == vsum_sq3_1 && llsum_sq3_2[5] == vsum_sq3_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 0, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 1, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 2, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 3, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 4, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 5, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_2, 6, vsum_sq3_3);
    assert(llsum_sq3_3[0] == dx && llsum_sq3_3[1] == dy && llsum_sq3_3[2] == dz && llsum_sq3_3[3] == vsum_sq3_0 && llsum_sq3_3[4] == vsum_sq3_1 && llsum_sq3_3[5] == vsum_sq3_2 && llsum_sq3_3[6] == vsum_sq3_3) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 0, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 1, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 2, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 3, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 4, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 5, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 6, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_3, 7, vsum_sq3_4);
    assert(llsum_sq3_4[0] == dx && llsum_sq3_4[1] == dy && llsum_sq3_4[2] == dz && llsum_sq3_4[3] == vsum_sq3_0 && llsum_sq3_4[4] == vsum_sq3_1 && llsum_sq3_4[5] == vsum_sq3_2 && llsum_sq3_4[6] == vsum_sq3_3 && llsum_sq3_4[7] == vsum_sq3_4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_sum_sq3_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_mulw(KExpr::Loc(0), KExpr::Loc(0), st, bufa, bufb);
    u_kexec_assign(3, KExpr::MulW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    let ssum_sq3_0 = mk_state(llsum_sq3_0, st.out);
    assert(kexec(stmt_sum_sq3_0(), st, bufa, bufb) == ssum_sq3_0 && ssum_sq3_0.locals == llsum_sq3_0 && ssum_sq3_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_0, addloop.mk_state]
    };

    u_seq_sum_sq3_1(ssum_sq3_0, bufa, bufb);
    u_keval_loc(1, ssum_sq3_0, bufa, bufb);
    u_keval_loc(1, ssum_sq3_0, bufa, bufb);
    u_keval_mulw(KExpr::Loc(1), KExpr::Loc(1), ssum_sq3_0, bufa, bufb);
    u_kexec_assign(4, KExpr::MulW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(1))), ssum_sq3_0, bufa, bufb);
    let ssum_sq3_1 = mk_state(llsum_sq3_1, st.out);
    assert(kexec(stmt_sum_sq3_1(), ssum_sq3_0, bufa, bufb) == ssum_sq3_1 && ssum_sq3_1.locals == llsum_sq3_1 && ssum_sq3_1.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_1, addloop.mk_state]
    };

    u_seq_sum_sq3_2(ssum_sq3_1, bufa, bufb);
    u_keval_loc(2, ssum_sq3_1, bufa, bufb);
    u_keval_loc(2, ssum_sq3_1, bufa, bufb);
    u_keval_mulw(KExpr::Loc(2), KExpr::Loc(2), ssum_sq3_1, bufa, bufb);
    u_kexec_assign(5, KExpr::MulW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(2))), ssum_sq3_1, bufa, bufb);
    let ssum_sq3_2 = mk_state(llsum_sq3_2, st.out);
    assert(kexec(stmt_sum_sq3_2(), ssum_sq3_1, bufa, bufb) == ssum_sq3_2 && ssum_sq3_2.locals == llsum_sq3_2 && ssum_sq3_2.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_2, addloop.mk_state]
    };

    u_seq_sum_sq3_3(ssum_sq3_2, bufa, bufb);
    u_keval_loc(3, ssum_sq3_2, bufa, bufb);
    u_keval_loc(4, ssum_sq3_2, bufa, bufb);
    u_keval_addw(KExpr::Loc(3), KExpr::Loc(4), ssum_sq3_2, bufa, bufb);
    u_kexec_assign(6, KExpr::AddW(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), ssum_sq3_2, bufa, bufb);
    let ssum_sq3_3 = mk_state(llsum_sq3_3, st.out);
    assert(kexec(stmt_sum_sq3_3(), ssum_sq3_2, bufa, bufb) == ssum_sq3_3 && ssum_sq3_3.locals == llsum_sq3_3 && ssum_sq3_3.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_3, addloop.mk_state]
    };

    u_keval_loc(6, ssum_sq3_3, bufa, bufb);
    u_keval_loc(5, ssum_sq3_3, bufa, bufb);
    u_keval_addw(KExpr::Loc(6), KExpr::Loc(5), ssum_sq3_3, bufa, bufb);
    u_kexec_assign(7, KExpr::AddW(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(5))), ssum_sq3_3, bufa, bufb);
    let ssum_sq3_4 = mk_state(llsum_sq3_4, st.out);
    assert(kexec(stmt_sum_sq3_4(), ssum_sq3_3, bufa, bufb) == ssum_sq3_4 && ssum_sq3_4.locals == llsum_sq3_4 && ssum_sq3_4.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_4, addloop.mk_state]
    };

    assert(kexec(body_sum_sq3(), st, bufa, bufb) == ssum_sq3_4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert((dx as int) * (dx as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert((dy as int) * (dy as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert((dz as int) * (dz as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert(vsum_sq3_4 as int == spec_sum_sq3(dx as int, dy as int, dz as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_sum_sq3, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

// ══════════ loop kernel: add_limbs ══════════

/// Written output value for iteration i (canonical spec).
pub open spec fn step_val_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, c0: u32, i: nat) -> u32 {
    wadd(wadd(bufa[i as int], bufb[i as int]), c0)
}

/// Carried-register value after iteration i (canonical spec).
pub open spec fn step_c0_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, c0: u32, i: nat) -> u32 {
    wadd(ltu(wadd(bufa[i as int], bufb[i as int]), bufa[i as int]), ltu(wadd(wadd(bufa[i as int], bufb[i as int]), c0), wadd(bufa[i as int], bufb[i as int])))
}

pub open spec fn model_out_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, out: Seq<u32>, c0: u32, lo: nat, n: nat) -> Seq<u32>
    decreases n - lo,
{
    if lo >= n { out } else {
        model_out_add_limbs(bufa, bufb, out.update(lo as int, step_val_add_limbs(bufa, bufb, c0, lo)), step_c0_add_limbs(bufa, bufb, c0, lo), lo + 1, n)
    }
}

pub open spec fn model_c0_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, c0: u32, lo: nat, n: nat) -> u32
    decreases n - lo,
{
    if lo >= n { c0 } else {
        model_c0_add_limbs(bufa, bufb, step_c0_add_limbs(bufa, bufb, c0, lo), lo + 1, n)
    }
}

pub proof fn u_model_out_step_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, out: Seq<u32>, c0: u32, lo: nat, n: nat)
    requires lo < n,
    ensures
        model_out_add_limbs(bufa, bufb, out, c0, lo, n)
            == model_out_add_limbs(bufa, bufb, out.update(lo as int, step_val_add_limbs(bufa, bufb, c0, lo)), step_c0_add_limbs(bufa, bufb, c0, lo), lo + 1, n),
{
}

pub proof fn u_model_out_done_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, out: Seq<u32>, c0: u32, lo: nat, n: nat)
    requires lo >= n,
    ensures
        model_out_add_limbs(bufa, bufb, out, c0, lo, n) == out,
{
}

pub proof fn u_model_c0_step_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, c0: u32, lo: nat, n: nat)
    requires lo < n,
    ensures
        model_c0_add_limbs(bufa, bufb, c0, lo, n)
            == model_c0_add_limbs(bufa, bufb, step_c0_add_limbs(bufa, bufb, c0, lo), lo + 1, n),
{
}

pub proof fn u_model_c0_done_add_limbs(bufa: Seq<u32>, bufb: Seq<u32>, c0: u32, lo: nat, n: nat)
    requires lo >= n,
    ensures
        model_c0_add_limbs(bufa, bufb, c0, lo, n) == c0,
{
}

pub open spec fn stmt_add_limbs_0() -> KStmt {
    KStmt::Assign { loc: 2, rhs: KExpr::ReadA(Box::new(KExpr::Loc(1))) }
}

pub open spec fn stmt_add_limbs_1() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::ReadB(Box::new(KExpr::Loc(1))) }
}

pub open spec fn stmt_add_limbs_2() -> KStmt {
    KStmt::Assign { loc: 4, rhs: KExpr::AddW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))) }
}

pub open spec fn stmt_add_limbs_3() -> KStmt {
    KStmt::Assign { loc: 5, rhs: KExpr::LtU(Box::new(KExpr::Loc(4)), Box::new(KExpr::Loc(2))) }
}

pub open spec fn stmt_add_limbs_4() -> KStmt {
    KStmt::Assign { loc: 6, rhs: KExpr::AddW(Box::new(KExpr::Loc(4)), Box::new(KExpr::Loc(0))) }
}

pub open spec fn stmt_add_limbs_5() -> KStmt {
    KStmt::Assign { loc: 7, rhs: KExpr::LtU(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(4))) }
}

pub open spec fn stmt_add_limbs_6() -> KStmt {
    KStmt::WriteOut { idx: KExpr::Loc(1), val: KExpr::Loc(6) }
}

pub open spec fn stmt_add_limbs_7() -> KStmt {
    KStmt::Assign { loc: 0, rhs: KExpr::AddW(Box::new(KExpr::Loc(5)), Box::new(KExpr::Loc(7))) }
}

pub open spec fn chain_add_limbs_6() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_6()), Box::new(stmt_add_limbs_7()))
}

pub open spec fn chain_add_limbs_5() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_5()), Box::new(chain_add_limbs_6()))
}

pub open spec fn chain_add_limbs_4() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_4()), Box::new(chain_add_limbs_5()))
}

pub open spec fn chain_add_limbs_3() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_3()), Box::new(chain_add_limbs_4()))
}

pub open spec fn chain_add_limbs_2() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_2()), Box::new(chain_add_limbs_3()))
}

pub open spec fn chain_add_limbs_1() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_1()), Box::new(chain_add_limbs_2()))
}

pub open spec fn chain_add_limbs_0() -> KStmt {
    KStmt::Seq2(Box::new(stmt_add_limbs_0()), Box::new(chain_add_limbs_1()))
}

pub open spec fn body_add_limbs() -> KStmt { chain_add_limbs_0() }

pub proof fn u_seq_add_limbs_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(body_add_limbs(), st, bufa, bufb)
            == kexec(chain_add_limbs_1(), kexec(stmt_add_limbs_0(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_1(), st, bufa, bufb)
            == kexec(chain_add_limbs_2(), kexec(stmt_add_limbs_1(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_2(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_2(), st, bufa, bufb)
            == kexec(chain_add_limbs_3(), kexec(stmt_add_limbs_2(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_3(), st, bufa, bufb)
            == kexec(chain_add_limbs_4(), kexec(stmt_add_limbs_3(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_4(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_4(), st, bufa, bufb)
            == kexec(chain_add_limbs_5(), kexec(stmt_add_limbs_4(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_5(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_5(), st, bufa, bufb)
            == kexec(chain_add_limbs_6(), kexec(stmt_add_limbs_5(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_add_limbs_6(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_add_limbs_6(), st, bufa, bufb)
            == kexec(stmt_add_limbs_7(), kexec(stmt_add_limbs_6(), st, bufa, bufb), bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
        (i as int) < bufa.len(),
    ensures
        kexec(stmt_add_limbs_0(), st, bufa, bufb)
            == mk_state(st.locals.update(2, bufa[i as int]), st.out),
{
    assert((i as u32) as int == i as int) by {
        intros
        push_cast
        omega
    };
    u_keval_loc(1, st, bufa, bufb);
    u_keval_reada(KExpr::Loc(1), st, bufa, bufb);
    u_kexec_assign(2, KExpr::ReadA(Box::new(KExpr::Loc(1))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_0(), st, bufa, bufb) == mk_state(st.locals.update(2, bufa[i as int]), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_0, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
        (i as int) < bufb.len(),
    ensures
        kexec(stmt_add_limbs_1(), st, bufa, bufb)
            == mk_state(st.locals.update(3, bufb[i as int]), st.out),
{
    assert((i as u32) as int == i as int) by {
        intros
        push_cast
        omega
    };
    u_keval_loc(1, st, bufa, bufb);
    u_keval_readb(KExpr::Loc(1), st, bufa, bufb);
    u_kexec_assign(3, KExpr::ReadB(Box::new(KExpr::Loc(1))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_1(), st, bufa, bufb) == mk_state(st.locals.update(3, bufb[i as int]), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_1, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_2(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
    ensures
        kexec(stmt_add_limbs_2(), st, bufa, bufb)
            == mk_state(st.locals.update(4, wadd(st.locals[2], st.locals[3])), st.out),
{
    u_keval_loc(2, st, bufa, bufb);
    u_keval_loc(3, st, bufa, bufb);
    u_keval_addw(KExpr::Loc(2), KExpr::Loc(3), st, bufa, bufb);
    u_kexec_assign(4, KExpr::AddW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_2(), st, bufa, bufb) == mk_state(st.locals.update(4, wadd(st.locals[2], st.locals[3])), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_2, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
    ensures
        kexec(stmt_add_limbs_3(), st, bufa, bufb)
            == mk_state(st.locals.update(5, ltu(st.locals[4], st.locals[2])), st.out),
{
    u_keval_loc(4, st, bufa, bufb);
    u_keval_loc(2, st, bufa, bufb);
    u_keval_ltu(KExpr::Loc(4), KExpr::Loc(2), st, bufa, bufb);
    u_kexec_assign(5, KExpr::LtU(Box::new(KExpr::Loc(4)), Box::new(KExpr::Loc(2))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_3(), st, bufa, bufb) == mk_state(st.locals.update(5, ltu(st.locals[4], st.locals[2])), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_3, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_4(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
    ensures
        kexec(stmt_add_limbs_4(), st, bufa, bufb)
            == mk_state(st.locals.update(6, wadd(st.locals[4], st.locals[0])), st.out),
{
    u_keval_loc(4, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_addw(KExpr::Loc(4), KExpr::Loc(0), st, bufa, bufb);
    u_kexec_assign(6, KExpr::AddW(Box::new(KExpr::Loc(4)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_4(), st, bufa, bufb) == mk_state(st.locals.update(6, wadd(st.locals[4], st.locals[0])), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_4, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_5(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
    ensures
        kexec(stmt_add_limbs_5(), st, bufa, bufb)
            == mk_state(st.locals.update(7, ltu(st.locals[6], st.locals[4])), st.out),
{
    u_keval_loc(6, st, bufa, bufb);
    u_keval_loc(4, st, bufa, bufb);
    u_keval_ltu(KExpr::Loc(6), KExpr::Loc(4), st, bufa, bufb);
    u_kexec_assign(7, KExpr::LtU(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(4))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_5(), st, bufa, bufb) == mk_state(st.locals.update(7, ltu(st.locals[6], st.locals[4])), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_5, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_6(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
        (i as int) < st.out.len(),
    ensures
        kexec(stmt_add_limbs_6(), st, bufa, bufb)
            == mk_state(st.locals, st.out.update(i as int, st.locals[6])),
{
    assert((i as u32) as int == i as int) by {
        intros
        push_cast
        omega
    };
    u_keval_loc(1, st, bufa, bufb);
    u_keval_loc(6, st, bufa, bufb);
    u_kexec_writeout(KExpr::Loc(1), KExpr::Loc(6), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_6(), st, bufa, bufb) == mk_state(st.locals, st.out.update(i as int, st.locals[6]))) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_6, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lstep_add_limbs_7(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
    ensures
        kexec(stmt_add_limbs_7(), st, bufa, bufb)
            == mk_state(st.locals.update(0, wadd(st.locals[5], st.locals[7])), st.out),
{
    u_keval_loc(5, st, bufa, bufb);
    u_keval_loc(7, st, bufa, bufb);
    u_keval_addw(KExpr::Loc(5), KExpr::Loc(7), st, bufa, bufb);
    u_kexec_assign(0, KExpr::AddW(Box::new(KExpr::Loc(5)), Box::new(KExpr::Loc(7))), st, bufa, bufb);
    assert(kexec(stmt_add_limbs_7(), st, bufa, bufb) == mk_state(st.locals.update(0, wadd(st.locals[5], st.locals[7])), st.out)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_add_limbs_7, addloop.mk_state]
    };
}

#[verifier::tactus_auto]
pub proof fn lemma_step_bisim_add_limbs(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, i: nat)
    requires
        st.locals.len() == 8,
        st.locals[1] == i as u32,
        i < 0x1_0000_0000,
        (i as int) < bufa.len(),
        (i as int) < bufb.len(),
        (i as int) < st.out.len(),
    ensures
        kexec(body_add_limbs(), st, bufa, bufb).locals.len() == 8,
        kexec(body_add_limbs(), st, bufa, bufb).locals[0] == step_c0_add_limbs(bufa, bufb, st.locals[0], i),
        kexec(body_add_limbs(), st, bufa, bufb).locals[1] == st.locals[1],
        kexec(body_add_limbs(), st, bufa, bufb).out == st.out.update(i as int, step_val_add_limbs(bufa, bufb, st.locals[0], i)),
{
    let l = st.locals;
    let tv0 = bufa[i as int];
    let tv1 = bufb[i as int];
    let tv2 = wadd(tv0, tv1);
    let tv3 = ltu(tv2, tv0);
    let tv4 = wadd(tv2, l[0]);
    let tv5 = ltu(tv4, tv2);
    let cnew = wadd(tv3, tv5);
    let ll0 = l.update(2, tv0);
    let ll1 = ll0.update(3, tv1);
    let ll2 = ll1.update(4, tv2);
    let ll3 = ll2.update(5, tv3);
    let ll4 = ll3.update(6, tv4);
    let ll5 = ll4.update(7, tv5);
    let outw = st.out.update(i as int, tv4);
    let ll6 = ll5.update(0, cnew);

    vstd::seq::axiom_seq_update_len::<u32>(l, 2, tv0);
    vstd::seq::axiom_seq_update_len::<u32>(ll0, 3, tv1);
    vstd::seq::axiom_seq_update_len::<u32>(ll1, 4, tv2);
    vstd::seq::axiom_seq_update_len::<u32>(ll2, 5, tv3);
    vstd::seq::axiom_seq_update_len::<u32>(ll3, 6, tv4);
    vstd::seq::axiom_seq_update_len::<u32>(ll4, 7, tv5);
    vstd::seq::axiom_seq_update_len::<u32>(ll5, 0, cnew);
    assert(ll0.len() == 8 && ll1.len() == 8 && ll2.len() == 8 && ll3.len() == 8 && ll4.len() == 8 && ll5.len() == 8 && ll6.len() == 8) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(l, 0, 2, tv0);
    vstd::seq::axiom_seq_update_different::<u32>(l, 1, 2, tv0);
    vstd::seq::axiom_seq_update_same::<u32>(l, 2, tv0);
    assert(ll0[0] == l[0] && ll0[1] == i as u32 && ll0[2] == tv0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(ll0, 0, 3, tv1);
    vstd::seq::axiom_seq_update_different::<u32>(ll0, 1, 3, tv1);
    vstd::seq::axiom_seq_update_different::<u32>(ll0, 2, 3, tv1);
    vstd::seq::axiom_seq_update_same::<u32>(ll0, 3, tv1);
    assert(ll1[0] == l[0] && ll1[1] == i as u32 && ll1[2] == tv0 && ll1[3] == tv1) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(ll1, 0, 4, tv2);
    vstd::seq::axiom_seq_update_different::<u32>(ll1, 1, 4, tv2);
    vstd::seq::axiom_seq_update_different::<u32>(ll1, 2, 4, tv2);
    vstd::seq::axiom_seq_update_different::<u32>(ll1, 3, 4, tv2);
    vstd::seq::axiom_seq_update_same::<u32>(ll1, 4, tv2);
    assert(ll2[0] == l[0] && ll2[1] == i as u32 && ll2[2] == tv0 && ll2[3] == tv1 && ll2[4] == tv2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(ll2, 0, 5, tv3);
    vstd::seq::axiom_seq_update_different::<u32>(ll2, 1, 5, tv3);
    vstd::seq::axiom_seq_update_different::<u32>(ll2, 2, 5, tv3);
    vstd::seq::axiom_seq_update_different::<u32>(ll2, 3, 5, tv3);
    vstd::seq::axiom_seq_update_different::<u32>(ll2, 4, 5, tv3);
    vstd::seq::axiom_seq_update_same::<u32>(ll2, 5, tv3);
    assert(ll3[0] == l[0] && ll3[1] == i as u32 && ll3[2] == tv0 && ll3[3] == tv1 && ll3[4] == tv2 && ll3[5] == tv3) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(ll3, 0, 6, tv4);
    vstd::seq::axiom_seq_update_different::<u32>(ll3, 1, 6, tv4);
    vstd::seq::axiom_seq_update_different::<u32>(ll3, 2, 6, tv4);
    vstd::seq::axiom_seq_update_different::<u32>(ll3, 3, 6, tv4);
    vstd::seq::axiom_seq_update_different::<u32>(ll3, 4, 6, tv4);
    vstd::seq::axiom_seq_update_different::<u32>(ll3, 5, 6, tv4);
    vstd::seq::axiom_seq_update_same::<u32>(ll3, 6, tv4);
    assert(ll4[0] == l[0] && ll4[1] == i as u32 && ll4[2] == tv0 && ll4[3] == tv1 && ll4[4] == tv2 && ll4[5] == tv3 && ll4[6] == tv4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(ll4, 0, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 1, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 2, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 3, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 4, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 5, 7, tv5);
    vstd::seq::axiom_seq_update_different::<u32>(ll4, 6, 7, tv5);
    vstd::seq::axiom_seq_update_same::<u32>(ll4, 7, tv5);
    assert(ll5[0] == l[0] && ll5[1] == i as u32 && ll5[2] == tv0 && ll5[3] == tv1 && ll5[4] == tv2 && ll5[5] == tv3 && ll5[6] == tv4 && ll5[7] == tv5) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_same::<u32>(ll5, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 1, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 2, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 3, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 4, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 5, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 6, 0, cnew);
    vstd::seq::axiom_seq_update_different::<u32>(ll5, 7, 0, cnew);
    assert(ll6[0] == cnew && ll6[1] == i as u32 && ll6[2] == tv0 && ll6[3] == tv1 && ll6[4] == tv2 && ll6[5] == tv3 && ll6[6] == tv4 && ll6[7] == tv5) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_add_limbs_0(st, bufa, bufb);
    lstep_add_limbs_0(st, bufa, bufb, i);
    let gs0 = mk_state(ll0, st.out);
    assert(kexec(stmt_add_limbs_0(), st, bufa, bufb) == gs0 && gs0.locals == ll0 && gs0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_1(gs0, bufa, bufb);
    lstep_add_limbs_1(gs0, bufa, bufb, i);
    let gs1 = mk_state(ll1, st.out);
    assert(kexec(stmt_add_limbs_1(), gs0, bufa, bufb) == gs1 && gs1.locals == ll1 && gs1.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_2(gs1, bufa, bufb);
    lstep_add_limbs_2(gs1, bufa, bufb, i);
    let gs2 = mk_state(ll2, st.out);
    assert(kexec(stmt_add_limbs_2(), gs1, bufa, bufb) == gs2 && gs2.locals == ll2 && gs2.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_3(gs2, bufa, bufb);
    lstep_add_limbs_3(gs2, bufa, bufb, i);
    let gs3 = mk_state(ll3, st.out);
    assert(kexec(stmt_add_limbs_3(), gs2, bufa, bufb) == gs3 && gs3.locals == ll3 && gs3.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_4(gs3, bufa, bufb);
    lstep_add_limbs_4(gs3, bufa, bufb, i);
    let gs4 = mk_state(ll4, st.out);
    assert(kexec(stmt_add_limbs_4(), gs3, bufa, bufb) == gs4 && gs4.locals == ll4 && gs4.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_5(gs4, bufa, bufb);
    lstep_add_limbs_5(gs4, bufa, bufb, i);
    let gs5 = mk_state(ll5, st.out);
    assert(kexec(stmt_add_limbs_5(), gs4, bufa, bufb) == gs5 && gs5.locals == ll5 && gs5.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    u_seq_add_limbs_6(gs5, bufa, bufb);
    lstep_add_limbs_6(gs5, bufa, bufb, i);
    let gs6 = mk_state(ll5, outw);
    assert(kexec(stmt_add_limbs_6(), gs5, bufa, bufb) == gs6 && gs6.locals == ll5 && gs6.out == outw) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    lstep_add_limbs_7(gs6, bufa, bufb, i);
    let gs7 = mk_state(ll6, outw);
    assert(kexec(stmt_add_limbs_7(), gs6, bufa, bufb) == gs7 && gs7.locals == ll6 && gs7.out == outw) by {
        intros
        simp_all (config := { zetaDelta := true }) [addloop.mk_state]
    };

    assert(kexec(body_add_limbs(), st, bufa, bufb) == gs7) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert(cnew == step_c0_add_limbs(bufa, bufb, l[0], i) && tv4 == step_val_add_limbs(bufa, bufb, l[0], i)) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.step_c0_add_limbs, gen_certs.step_val_add_limbs]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

#[verifier::tactus_auto]
pub proof fn lemma_loop_bisim_add_limbs(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, lo: nat, n: nat)
    requires
        st.locals.len() == 8,
        lo <= n,
        n <= bufa.len(),
        n <= bufb.len(),
        (n as int) <= st.out.len(),
        n < 0x1_0000_0000,
    ensures
        kloop(body_add_limbs(), 1, lo, n, st, bufa, bufb).locals.len() == 8,
        kloop(body_add_limbs(), 1, lo, n, st, bufa, bufb).locals[0]
            == model_c0_add_limbs(bufa, bufb, st.locals[0], lo, n),
        kloop(body_add_limbs(), 1, lo, n, st, bufa, bufb).out
            == model_out_add_limbs(bufa, bufb, st.out, st.locals[0], lo, n),
        kloop(body_add_limbs(), 1, lo, n, st, bufa, bufb).out.len() == st.out.len(),
    decreases n - lo,
{
    if lo >= n {
        u_kloop_done(body_add_limbs(), 1, lo, n, st, bufa, bufb);
        u_model_out_done_add_limbs(bufa, bufb, st.out, st.locals[0], lo, n);
        u_model_c0_done_add_limbs(bufa, bufb, st.locals[0], lo, n);
    } else {
        let stl = mk_state(st.locals.update(1, lo as u32), st.out);
        u_kloop_step(body_add_limbs(), 1, lo, n, st, bufa, bufb);
        vstd::seq::axiom_seq_update_len::<u32>(st.locals, 1, lo as u32);
        vstd::seq::axiom_seq_update_same::<u32>(st.locals, 1, lo as u32);
        vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 1, lo as u32);
        assert(stl.locals.len() == 8 && stl.locals[1] == lo as u32
            && stl.locals[0] == st.locals[0] && stl.out == st.out) by {
            intros
            simp_all (config := { zetaDelta := true }) [addloop.mk_state]
        };
        assert(lo < 0x1_0000_0000 && (lo as int) < bufa.len() && (lo as int) < bufb.len()
            && (lo as int) < stl.out.len()) by {
            intros
            omega
        };

        lemma_step_bisim_add_limbs(stl, bufa, bufb, lo);
        let st2 = kexec(body_add_limbs(), stl, bufa, bufb);
        vstd::seq::axiom_seq_update_len::<u32>(st.out, lo as int, step_val_add_limbs(bufa, bufb, st.locals[0], lo));
        assert(st2.locals.len() == 8 && (n as int) <= st2.out.len()
            && st2.out.len() == st.out.len()
            && st2.locals[0] == step_c0_add_limbs(bufa, bufb, st.locals[0], lo)
            && st2.out == st.out.update(lo as int, step_val_add_limbs(bufa, bufb, st.locals[0], lo))) by {
            intros
            simp_all (config := { zetaDelta := true }) []
        };

        lemma_loop_bisim_add_limbs(st2, bufa, bufb, lo + 1, n);
        u_model_out_step_add_limbs(bufa, bufb, st.out, st.locals[0], lo, n);
        u_model_c0_step_add_limbs(bufa, bufb, st.locals[0], lo, n);
        assert(kloop(body_add_limbs(), 1, lo, n, st, bufa, bufb)
            == kloop(body_add_limbs(), 1, lo + 1, n, st2, bufa, bufb)) by {
            intros
            simp_all (config := { zetaDelta := true }) [addloop.mk_state]
        };
    }
}

} // verus!
