//! GENERATED by kirgen — do not edit. Regenerate: cargo run --manifest-path ../kirgen/Cargo.toml
//!
//! Certificates for expression kernels: for each kernel, the KIR literal
//! provably computes the kernel's functional spec (spec_kernels::*), which
//! the verified source exec fn already provably returns. Chain complete:
//! source exec == spec == KIR.

use vstd::prelude::*;
use crate::kir::*;
use crate::addloop::mk_state;
use crate::addloop::{u_keval_loc, u_keval_addw, u_kexec_assign};
use crate::spec_kernels::*;

verus! {

// Generic one-step unfolds for the extended op set (schema; empty bodies).

pub proof fn u_keval_subw(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::SubW(Box::new(x), Box::new(y)), st, bufa, bufb)
            == wsub(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_mulw(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::MulW(Box::new(x), Box::new(y)), st, bufa, bufb)
            == wmul(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_geu(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::GeU(Box::new(x), Box::new(y)), st, bufa, bufb)
            == geu(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_leu(x: KExpr, y: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::LeU(Box::new(x), Box::new(y)), st, bufa, bufb)
            == leu(keval(x, st, bufa, bufb), keval(y, st, bufa, bufb)),
{
}

pub proof fn u_keval_select(c: KExpr, t: KExpr, e: KExpr, st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        keval(KExpr::Select(Box::new(c), Box::new(t), Box::new(e)), st, bufa, bufb)
            == (if keval(c, st, bufa, bufb) != 0 {
                keval(t, st, bufa, bufb)
            } else {
                keval(e, st, bufa, bufb)
            }),
{
}

// ══════════ kernel: abs_delta ══════════

pub open spec fn stmt_abs_delta_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))) }
}

pub open spec fn body_abs_delta() -> KStmt { stmt_abs_delta_0() }

pub proof fn u_seq_abs_delta_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures kexec(body_abs_delta(), st, bufa, bufb) == kexec(stmt_abs_delta_0(), st, bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_abs_delta(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, a: u32, b: u32, n: u32)
    requires
        st.locals.len() == 4,
        st.locals[0] == a,
        st.locals[1] == b,
        st.locals[2] == n,
        1 <= n,
        n <= 1024,
        a < n,
        b < n,
    ensures
        kexec(body_abs_delta(), st, bufa, bufb).locals.len() == 4,
        kexec(body_abs_delta(), st, bufa, bufb).locals[3] as int == spec_abs_delta(a as int, b as int),
{
    let vabs_delta_0 = (if geu(a, b) != 0 { wsub(a, b) } else { wsub(b, a) });
    let llabs_delta_0 = st.locals.update(3, vabs_delta_0);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vabs_delta_0);
    assert(llabs_delta_0.len() == 4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vabs_delta_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vabs_delta_0);
    assert(llabs_delta_0[0] == a && llabs_delta_0[1] == b && llabs_delta_0[2] == n && llabs_delta_0[3] == vabs_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_abs_delta_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_geu(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(1), KExpr::Loc(0), st, bufa, bufb);
    u_keval_select(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    u_kexec_assign(3, KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))), st, bufa, bufb);
    let sabs_delta_0 = mk_state(llabs_delta_0, st.out);
    assert(kexec(stmt_abs_delta_0(), st, bufa, bufb) == sabs_delta_0 && sabs_delta_0.locals == llabs_delta_0 && sabs_delta_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_abs_delta_0, addloop.mk_state]
    };

    assert(kexec(body_abs_delta(), st, bufa, bufb) == sabs_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert(vabs_delta_0 as int == spec_abs_delta(a as int, b as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_abs_delta, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

// ══════════ kernel: wrap_delta ══════════

pub open spec fn stmt_wrap_delta_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))) }
}

pub open spec fn stmt_wrap_delta_1() -> KStmt {
    KStmt::Assign { loc: 4, rhs: KExpr::SubW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))) }
}

pub open spec fn stmt_wrap_delta_2() -> KStmt {
    KStmt::Assign { loc: 5, rhs: KExpr::Select(Box::new(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4)))), Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))) }
}

pub open spec fn chain_wrap_delta_1() -> KStmt {
    KStmt::Seq2(Box::new(stmt_wrap_delta_1()), Box::new(stmt_wrap_delta_2()))
}

pub open spec fn chain_wrap_delta_0() -> KStmt {
    KStmt::Seq2(Box::new(stmt_wrap_delta_0()), Box::new(chain_wrap_delta_1()))
}

pub open spec fn body_wrap_delta() -> KStmt { chain_wrap_delta_0() }

pub proof fn u_seq_wrap_delta_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(body_wrap_delta(), st, bufa, bufb)
            == kexec(chain_wrap_delta_1(), kexec(stmt_wrap_delta_0(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_wrap_delta_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_wrap_delta_1(), st, bufa, bufb)
            == kexec(stmt_wrap_delta_2(), kexec(stmt_wrap_delta_1(), st, bufa, bufb), bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_wrap_delta(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, a: u32, b: u32, n: u32)
    requires
        st.locals.len() == 6,
        st.locals[0] == a,
        st.locals[1] == b,
        st.locals[2] == n,
        1 <= n,
        n <= 1024,
        a < n,
        b < n,
    ensures
        kexec(body_wrap_delta(), st, bufa, bufb).locals.len() == 6,
        kexec(body_wrap_delta(), st, bufa, bufb).locals[5] as int == spec_wrap_delta(a as int, b as int, n as int),
{
    let vwrap_delta_0 = (if geu(a, b) != 0 { wsub(a, b) } else { wsub(b, a) });
    let vwrap_delta_1 = wsub(n, vwrap_delta_0);
    let vwrap_delta_2 = (if leu(vwrap_delta_0, vwrap_delta_1) != 0 { vwrap_delta_0 } else { vwrap_delta_1 });
    let llwrap_delta_0 = st.locals.update(3, vwrap_delta_0);
    let llwrap_delta_1 = llwrap_delta_0.update(4, vwrap_delta_1);
    let llwrap_delta_2 = llwrap_delta_1.update(5, vwrap_delta_2);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_len::<u32>(llwrap_delta_0, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_len::<u32>(llwrap_delta_1, 5, vwrap_delta_2);
    assert(llwrap_delta_0.len() == 6 && llwrap_delta_1.len() == 6 && llwrap_delta_2.len() == 6) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vwrap_delta_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vwrap_delta_0);
    assert(llwrap_delta_0[0] == a && llwrap_delta_0[1] == b && llwrap_delta_0[2] == n && llwrap_delta_0[3] == vwrap_delta_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 0, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 1, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 2, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_0, 3, 4, vwrap_delta_1);
    vstd::seq::axiom_seq_update_same::<u32>(llwrap_delta_0, 4, vwrap_delta_1);
    assert(llwrap_delta_1[0] == a && llwrap_delta_1[1] == b && llwrap_delta_1[2] == n && llwrap_delta_1[3] == vwrap_delta_0 && llwrap_delta_1[4] == vwrap_delta_1) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 0, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 1, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 2, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 3, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_different::<u32>(llwrap_delta_1, 4, 5, vwrap_delta_2);
    vstd::seq::axiom_seq_update_same::<u32>(llwrap_delta_1, 5, vwrap_delta_2);
    assert(llwrap_delta_2[0] == a && llwrap_delta_2[1] == b && llwrap_delta_2[2] == n && llwrap_delta_2[3] == vwrap_delta_0 && llwrap_delta_2[4] == vwrap_delta_1 && llwrap_delta_2[5] == vwrap_delta_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_wrap_delta_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_geu(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(0), KExpr::Loc(1), st, bufa, bufb);
    u_keval_loc(1, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_subw(KExpr::Loc(1), KExpr::Loc(0), st, bufa, bufb);
    u_keval_select(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1))), KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    u_kexec_assign(3, KExpr::Select(Box::new(KExpr::GeU(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(1)))), Box::new(KExpr::SubW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(0))))), st, bufa, bufb);
    let swrap_delta_0 = mk_state(llwrap_delta_0, st.out);
    assert(kexec(stmt_wrap_delta_0(), st, bufa, bufb) == swrap_delta_0 && swrap_delta_0.locals == llwrap_delta_0 && swrap_delta_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_0, addloop.mk_state]
    };

    u_seq_wrap_delta_1(swrap_delta_0, bufa, bufb);
    u_keval_loc(2, swrap_delta_0, bufa, bufb);
    u_keval_loc(3, swrap_delta_0, bufa, bufb);
    u_keval_subw(KExpr::Loc(2), KExpr::Loc(3), swrap_delta_0, bufa, bufb);
    u_kexec_assign(4, KExpr::SubW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(3))), swrap_delta_0, bufa, bufb);
    let swrap_delta_1 = mk_state(llwrap_delta_1, st.out);
    assert(kexec(stmt_wrap_delta_1(), swrap_delta_0, bufa, bufb) == swrap_delta_1 && swrap_delta_1.locals == llwrap_delta_1 && swrap_delta_1.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_1, addloop.mk_state]
    };

    u_keval_loc(3, swrap_delta_1, bufa, bufb);
    u_keval_loc(4, swrap_delta_1, bufa, bufb);
    u_keval_leu(KExpr::Loc(3), KExpr::Loc(4), swrap_delta_1, bufa, bufb);
    u_keval_loc(3, swrap_delta_1, bufa, bufb);
    u_keval_loc(4, swrap_delta_1, bufa, bufb);
    u_keval_select(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), KExpr::Loc(3), KExpr::Loc(4), swrap_delta_1, bufa, bufb);
    u_kexec_assign(5, KExpr::Select(Box::new(KExpr::LeU(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4)))), Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), swrap_delta_1, bufa, bufb);
    let swrap_delta_2 = mk_state(llwrap_delta_2, st.out);
    assert(kexec(stmt_wrap_delta_2(), swrap_delta_1, bufa, bufb) == swrap_delta_2 && swrap_delta_2.locals == llwrap_delta_2 && swrap_delta_2.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_wrap_delta_2, addloop.mk_state]
    };

    assert(kexec(body_wrap_delta(), st, bufa, bufb) == swrap_delta_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert(vwrap_delta_2 as int == spec_wrap_delta(a as int, b as int, n as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_wrap_delta, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

// ══════════ kernel: sum_sq3 ══════════

pub open spec fn stmt_sum_sq3_0() -> KStmt {
    KStmt::Assign { loc: 3, rhs: KExpr::MulW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(0))) }
}

pub open spec fn stmt_sum_sq3_1() -> KStmt {
    KStmt::Assign { loc: 4, rhs: KExpr::MulW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(1))) }
}

pub open spec fn stmt_sum_sq3_2() -> KStmt {
    KStmt::Assign { loc: 5, rhs: KExpr::MulW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(2))) }
}

pub open spec fn stmt_sum_sq3_3() -> KStmt {
    KStmt::Assign { loc: 6, rhs: KExpr::AddW(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))) }
}

pub open spec fn stmt_sum_sq3_4() -> KStmt {
    KStmt::Assign { loc: 7, rhs: KExpr::AddW(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(5))) }
}

pub open spec fn chain_sum_sq3_3() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_3()), Box::new(stmt_sum_sq3_4()))
}

pub open spec fn chain_sum_sq3_2() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_2()), Box::new(chain_sum_sq3_3()))
}

pub open spec fn chain_sum_sq3_1() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_1()), Box::new(chain_sum_sq3_2()))
}

pub open spec fn chain_sum_sq3_0() -> KStmt {
    KStmt::Seq2(Box::new(stmt_sum_sq3_0()), Box::new(chain_sum_sq3_1()))
}

pub open spec fn body_sum_sq3() -> KStmt { chain_sum_sq3_0() }

pub proof fn u_seq_sum_sq3_0(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(body_sum_sq3(), st, bufa, bufb)
            == kexec(chain_sum_sq3_1(), kexec(stmt_sum_sq3_0(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_1(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_1(), st, bufa, bufb)
            == kexec(chain_sum_sq3_2(), kexec(stmt_sum_sq3_1(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_2(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_2(), st, bufa, bufb)
            == kexec(chain_sum_sq3_3(), kexec(stmt_sum_sq3_2(), st, bufa, bufb), bufa, bufb),
{
}

pub proof fn u_seq_sum_sq3_3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>)
    ensures
        kexec(chain_sum_sq3_3(), st, bufa, bufb)
            == kexec(stmt_sum_sq3_4(), kexec(stmt_sum_sq3_3(), st, bufa, bufb), bufa, bufb),
{
}

#[verifier::tactus_auto]
pub proof fn cert_sum_sq3(st: KState, bufa: Seq<u32>, bufb: Seq<u32>, dx: u32, dy: u32, dz: u32)
    requires
        st.locals.len() == 8,
        st.locals[0] == dx,
        st.locals[1] == dy,
        st.locals[2] == dz,
        dx <= 512,
        dy <= 512,
        dz <= 1023,
    ensures
        kexec(body_sum_sq3(), st, bufa, bufb).locals.len() == 8,
        kexec(body_sum_sq3(), st, bufa, bufb).locals[7] as int == spec_sum_sq3(dx as int, dy as int, dz as int),
{
    let vsum_sq3_0 = wmul(dx, dx);
    let vsum_sq3_1 = wmul(dy, dy);
    let vsum_sq3_2 = wmul(dz, dz);
    let vsum_sq3_3 = wadd(vsum_sq3_0, vsum_sq3_1);
    let vsum_sq3_4 = wadd(vsum_sq3_3, vsum_sq3_2);
    let llsum_sq3_0 = st.locals.update(3, vsum_sq3_0);
    let llsum_sq3_1 = llsum_sq3_0.update(4, vsum_sq3_1);
    let llsum_sq3_2 = llsum_sq3_1.update(5, vsum_sq3_2);
    let llsum_sq3_3 = llsum_sq3_2.update(6, vsum_sq3_3);
    let llsum_sq3_4 = llsum_sq3_3.update(7, vsum_sq3_4);

    vstd::seq::axiom_seq_update_len::<u32>(st.locals, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_0, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_1, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_2, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_len::<u32>(llsum_sq3_3, 7, vsum_sq3_4);
    assert(llsum_sq3_0.len() == 8 && llsum_sq3_1.len() == 8 && llsum_sq3_2.len() == 8 && llsum_sq3_3.len() == 8 && llsum_sq3_4.len() == 8) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 0, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 1, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_different::<u32>(st.locals, 2, 3, vsum_sq3_0);
    vstd::seq::axiom_seq_update_same::<u32>(st.locals, 3, vsum_sq3_0);
    assert(llsum_sq3_0[0] == dx && llsum_sq3_0[1] == dy && llsum_sq3_0[2] == dz && llsum_sq3_0[3] == vsum_sq3_0) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 0, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 1, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 2, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_0, 3, 4, vsum_sq3_1);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_0, 4, vsum_sq3_1);
    assert(llsum_sq3_1[0] == dx && llsum_sq3_1[1] == dy && llsum_sq3_1[2] == dz && llsum_sq3_1[3] == vsum_sq3_0 && llsum_sq3_1[4] == vsum_sq3_1) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 0, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 1, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 2, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 3, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_1, 4, 5, vsum_sq3_2);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_1, 5, vsum_sq3_2);
    assert(llsum_sq3_2[0] == dx && llsum_sq3_2[1] == dy && llsum_sq3_2[2] == dz && llsum_sq3_2[3] == vsum_sq3_0 && llsum_sq3_2[4] == vsum_sq3_1 && llsum_sq3_2[5] == vsum_sq3_2) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 0, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 1, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 2, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 3, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 4, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_2, 5, 6, vsum_sq3_3);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_2, 6, vsum_sq3_3);
    assert(llsum_sq3_3[0] == dx && llsum_sq3_3[1] == dy && llsum_sq3_3[2] == dz && llsum_sq3_3[3] == vsum_sq3_0 && llsum_sq3_3[4] == vsum_sq3_1 && llsum_sq3_3[5] == vsum_sq3_2 && llsum_sq3_3[6] == vsum_sq3_3) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 0, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 1, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 2, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 3, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 4, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 5, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_different::<u32>(llsum_sq3_3, 6, 7, vsum_sq3_4);
    vstd::seq::axiom_seq_update_same::<u32>(llsum_sq3_3, 7, vsum_sq3_4);
    assert(llsum_sq3_4[0] == dx && llsum_sq3_4[1] == dy && llsum_sq3_4[2] == dz && llsum_sq3_4[3] == vsum_sq3_0 && llsum_sq3_4[4] == vsum_sq3_1 && llsum_sq3_4[5] == vsum_sq3_2 && llsum_sq3_4[6] == vsum_sq3_3 && llsum_sq3_4[7] == vsum_sq3_4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    u_seq_sum_sq3_0(st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_loc(0, st, bufa, bufb);
    u_keval_mulw(KExpr::Loc(0), KExpr::Loc(0), st, bufa, bufb);
    u_kexec_assign(3, KExpr::MulW(Box::new(KExpr::Loc(0)), Box::new(KExpr::Loc(0))), st, bufa, bufb);
    let ssum_sq3_0 = mk_state(llsum_sq3_0, st.out);
    assert(kexec(stmt_sum_sq3_0(), st, bufa, bufb) == ssum_sq3_0 && ssum_sq3_0.locals == llsum_sq3_0 && ssum_sq3_0.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_0, addloop.mk_state]
    };

    u_seq_sum_sq3_1(ssum_sq3_0, bufa, bufb);
    u_keval_loc(1, ssum_sq3_0, bufa, bufb);
    u_keval_loc(1, ssum_sq3_0, bufa, bufb);
    u_keval_mulw(KExpr::Loc(1), KExpr::Loc(1), ssum_sq3_0, bufa, bufb);
    u_kexec_assign(4, KExpr::MulW(Box::new(KExpr::Loc(1)), Box::new(KExpr::Loc(1))), ssum_sq3_0, bufa, bufb);
    let ssum_sq3_1 = mk_state(llsum_sq3_1, st.out);
    assert(kexec(stmt_sum_sq3_1(), ssum_sq3_0, bufa, bufb) == ssum_sq3_1 && ssum_sq3_1.locals == llsum_sq3_1 && ssum_sq3_1.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_1, addloop.mk_state]
    };

    u_seq_sum_sq3_2(ssum_sq3_1, bufa, bufb);
    u_keval_loc(2, ssum_sq3_1, bufa, bufb);
    u_keval_loc(2, ssum_sq3_1, bufa, bufb);
    u_keval_mulw(KExpr::Loc(2), KExpr::Loc(2), ssum_sq3_1, bufa, bufb);
    u_kexec_assign(5, KExpr::MulW(Box::new(KExpr::Loc(2)), Box::new(KExpr::Loc(2))), ssum_sq3_1, bufa, bufb);
    let ssum_sq3_2 = mk_state(llsum_sq3_2, st.out);
    assert(kexec(stmt_sum_sq3_2(), ssum_sq3_1, bufa, bufb) == ssum_sq3_2 && ssum_sq3_2.locals == llsum_sq3_2 && ssum_sq3_2.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_2, addloop.mk_state]
    };

    u_seq_sum_sq3_3(ssum_sq3_2, bufa, bufb);
    u_keval_loc(3, ssum_sq3_2, bufa, bufb);
    u_keval_loc(4, ssum_sq3_2, bufa, bufb);
    u_keval_addw(KExpr::Loc(3), KExpr::Loc(4), ssum_sq3_2, bufa, bufb);
    u_kexec_assign(6, KExpr::AddW(Box::new(KExpr::Loc(3)), Box::new(KExpr::Loc(4))), ssum_sq3_2, bufa, bufb);
    let ssum_sq3_3 = mk_state(llsum_sq3_3, st.out);
    assert(kexec(stmt_sum_sq3_3(), ssum_sq3_2, bufa, bufb) == ssum_sq3_3 && ssum_sq3_3.locals == llsum_sq3_3 && ssum_sq3_3.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_3, addloop.mk_state]
    };

    u_keval_loc(6, ssum_sq3_3, bufa, bufb);
    u_keval_loc(5, ssum_sq3_3, bufa, bufb);
    u_keval_addw(KExpr::Loc(6), KExpr::Loc(5), ssum_sq3_3, bufa, bufb);
    u_kexec_assign(7, KExpr::AddW(Box::new(KExpr::Loc(6)), Box::new(KExpr::Loc(5))), ssum_sq3_3, bufa, bufb);
    let ssum_sq3_4 = mk_state(llsum_sq3_4, st.out);
    assert(kexec(stmt_sum_sq3_4(), ssum_sq3_3, bufa, bufb) == ssum_sq3_4 && ssum_sq3_4.locals == llsum_sq3_4 && ssum_sq3_4.out == st.out) by {
        intros
        simp_all (config := { zetaDelta := true }) [gen_certs.stmt_sum_sq3_4, addloop.mk_state]
    };

    assert(kexec(body_sum_sq3(), st, bufa, bufb) == ssum_sq3_4) by {
        intros
        simp_all (config := { zetaDelta := true }) []
    };

    assert((dx as int) * (dx as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert((dy as int) * (dy as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert((dz as int) * (dz as int) < 0x1_0000_0000) by {
        intros
        simp_all (config := { zetaDelta := true }) [kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
    assert(vsum_sq3_4 as int == spec_sum_sq3(dx as int, dy as int, dz as int)) by {
        intros
        simp_all (config := { zetaDelta := true }) [spec_kernels.spec_sum_sq3, kir.wadd, kir.wsub, kir.wmul, kir.geu, kir.leu, kir.ltu]
        <;> (try split_ifs)
        <;> (try push_cast at *)
        <;> (first | omega | nlinarith)
    };
}

} // verus!
